version: '3'

services:
  peer:
    image: peer_v7:latest
    networks:
      - peer-server_default
    deploy:
      mode: replicated
      replicas: 2
    

networks:
  peer-server_default:
    external: true
