version: '3'

services:
  peer:
    image: peerb:latest
    networks:
      - peer-server_default
    deploy:
      mode: replicated
      replicas: 6
    

networks:
  peer-server_default:
    external: true
